version: 0.2

phases:
  pre_build:
    commands:
      - set -e
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.$ECR_REGION.amazonaws.com
      - export IMAGE_TAG="$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-8)"
  build:
    commands:
      - echo Building the Docker image...
      - IMAGE_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPO_NAME}"
      - docker build -t "${IMAGE_URL}:${IMAGE_TAG}" -t "${IMAGE_URL}:latest" .
  post_build:
    commands:
      - set -e
      - echo Pushing the Docker image...
      - docker push --all-tags "$IMAGE_URL"
      # - echo Writing image definitions file...
      # - echo "export IMAGE_URL=$IMAGE_URL" > build-output.sh

artifacts:
  files:
