server_name: auth
exchange_name: my_exchange.topic

db:
  redis:
    host: localhost
    port: 63791
    db: 0
    prefix: auth
  postgres:
    host: localhost
    user: auth_admin
    port: 54321
    database: auth
    password: ${ENV_DB_PASSWORD}
    ssl_path: ssl/ap-northeast-2-bundle.pem

rabbitmq:
  host: localhost
  port: 5672
  user: user
  password: ${ENV_RABBITMQ_PASSWORD}
  vhost: my_vhost

jwt:
  secret: ${ENV_JWT_SECRET}
  refresh_secret: ${ENV_JWT_REFRESH_SECRET}

sauron:
  repository_id: 5
  endpoint: http://localhost:8002/analyze

logger:
  level: DEBUG
