db:
  redis:
    host: localhost
    port: 63791
    db: 0
  postgres:
    host: localhost
    user: postgres
    port: 54321
    database: auth_db
    password: ENV_DB_PASSWORD

jwt:
  secret: ENV_JWT_SECRET
