server_name: auth
# exchange_name: my_exchange.topic

db:
  # redis:
  #   host: localhost
  #   port: 63791
  #   db: 0
  #   prefix: 'auth'
  postgres:
    host: mimir-auth-db.cxowigk2a8k5.ap-northeast-2.rds.amazonaws.com
    user: postgres
    port: 5432
    database: 'postgres'
    password: ENV_DB_PASSWORD

# rabbitmq:
#   host: localhost
#   port: 5672
#   user: user
#   password: ENV_RABBITMQ_PASSWORD
#   vhost: my_vhost
  
jwt:
  secret: ENV_JWT_SECRET
  refresh_secret: ENV_JWT_REFRESH_SECRET
