receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  prometheus/self:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 1s
          static_configs:
            - targets: ["0.0.0.0:8888"]

processors:
  batch:
    send_batch_size: 8192
    send_batch_max_size: 8192
    timeout: 1s
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15
  resourcedetection:
    detectors: [env, ecs]
    timeout: 5s
    override: false
  resource:
    attributes:
      - key: environment
        value: "dev"
        action: upsert
      - key: service.name
        value: "chat-svr"
        action: upsert
  resource/drop_ecs_metadata:
    attributes:
      - key: aws.ecs.cluster.arn
        action: delete
      - key: aws.ecs.task.arn
        action: delete
      - key: aws.ecs.task.family
        action: delete
      - key: aws.ecs.task.revision
        action: delete
      - key: aws.ecs.container.name
        action: delete
      - key: aws.ecs.launchtype
        action: delete
      - key: aws.log.group.arns
        action: delete
      - key: aws.log.group.names
        action: delete
      - key: aws.log.stream.arns
        action: delete
      - key: aws.log.stream.names
        action: delete
      - key: cloud.account.id
        action: delete
      - key: cloud.availability_zone
        action: delete
      - key: cloud.platform
        action: delete
      - key: cloud.provider
        action: delete
      - key: cloud.region
        action: delete
      - key: ecs.version
        action: delete
      - key: host.arch
        action: delete
      - key: process.command
        action: delete
      - key: process.command_args
        action: delete
      - key: process.executable.name
        action: delete
      - key: process.executable.path
        action: delete
      - key: process.owner
        action: delete
      - key: process.pid
        action: delete
      - key: process.runtime.description
        action: delete
      - key: process.runtime.name
        action: delete
      - key: process.runtime.version
        action: delete
      - key: scope.name
        action: delete
      - key: scope.version
        action: delete
      - key: telemetry.sdk.language
        action: delete
      - key: telemetry.sdk.version
        action: delete
      - key: telemetry.sdk.name
        action: delete
  attributes/logs_keep_single_trace_id:
    actions:
      # keep auto-instrumented trace_id only
      - key: trace.id
        action: delete
      - key: otelTraceID
        action: delete
      - key: otelSpanID
        action: delete

exporters:
  prometheusremotewrite:
    endpoint: http://victoriametrics:8428/api/v1/write

  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  otlphttp/logs:
    endpoint: "http://victorialogs:9428/insert/opentelemetry"

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus/self]
      processors: [memory_limiter, resourcedetection, resource, resource/drop_ecs_metadata, batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, resource/drop_ecs_metadata, batch]
      exporters: [otlp/jaeger]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, resource/drop_ecs_metadata, attributes/logs_keep_single_trace_id, batch]
      exporters: [otlphttp/logs, debug]
